"""initial

Revision ID: 8a2d48102f3
Revises: None
Create Date: 2014-04-18 15:48:50.964379

"""

# revision identifiers, used by Alembic.
revision = '8a2d48102f3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_virtualhosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('server_name', sa.String(length=60), nullable=False),
    sa.Column('bind_address', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bind_address'),
    sa.UniqueConstraint('server_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_virtualhosts')
    ### end Alembic commands ###
